export const CITIES = [
  {
    value: "beijing",
    label: "北京市",
    children: [{ value: "beijing", label: "北京市" }],
  },
  {
    value: "shanghai",
    label: "上海市",
    children: [{ value: "shanghai", label: "上海市" }],
  },
  {
    value: "guangdong",
    label: "广东省",
    children: [
      { value: "guangzhou", label: "广州市" },
      { value: "shenzhen", label: "深圳市" },
      { value: "zhuhai", label: "珠海市" },
      { value: "foshan", label: "佛山市" },
      { value: "dongguan", label: "东莞市" },
      { value: "zhongshan", label: "中山市" },
      { value: "jiangmen", label: "江门市" },
      { value: "huizhou", label: "惠州市" },
      { value: "meizhou", label: "梅州市" },
      { value: "shantou", label: "汕头市" },
      { value: "chaozhou", label: "潮州市" },
      { value: "yunfu", label: "云浮市" },
      { value: "qingyuan", label: "清远市" },
      { value: "yangjiang", label: "阳江市" },
      { value: "maoming", label: "茂名市" },
    ],
  },
  {
    value: "zhejiang",
    label: "浙江省",
    children: [
      { value: "hangzhou", label: "杭州市" },
      { value: "ningbo", label: "宁波市" },
      { value: "wenzhou", label: "温州市" },
      { value: "shaoxing", label: "绍兴市" },
      { value: "jiaxing", label: "嘉兴市" },
      { value: "huzhou", label: "湖州市" },
      { value: "lishui", label: "丽水市" },
      { value: "taizhou", label: "台州市" },
      { value: "quzhou", label: "衢州市" },
      { value: "jinhua", label: "金华市" },
      { value: "yiwu", label: "义乌市" },
    ],
  },
  {
    value: "jiangsu",
    label: "江苏省",
    children: [
      { value: "nanjing", label: "南京市" },
      { value: "suzhou", label: "苏州市" },
      { value: "wuxi", label: "无锡市" },
      { value: "changzhou", label: "常州市" },
      { value: "zhenjiang", label: "镇江市" },
      { value: "nantong", label: "南通市" },
      { value: "yangzhou", label: "扬州市" },
      { value: "taizhou", label: "泰州市" },
      { value: "suqian", label: "宿迁市" },
      { value: "xuzhou", label: "徐州市" },
      { value: "huaian", label: "淮安市" },
      { value: "lianyungang", label: "连云港市" },
      { value: "yancheng", label: "盐城市" },
    ],
  },
  {
    value: "anhui",
    label: "安徽省",
    children: [
      { value: "hefei", label: "合肥市" },
      { value: "bengbu", label: "蚌埠市" },
      { value: "wuhu", label: "芜湖市" },
      { value: "huainan", label: "淮南市" },
      { value: "maanshan", label: "马鞍山市" },
      { value: "anqing", label: "安庆市" },
      { value: "tongling", label: "铜陵市" },
      { value: "fuyang", label: "阜阳市" },
      { value: "huangshan", label: "黄山市" },
      { value: "chuzhou", label: "滁州市" },
    ],
  },
  {
    value: "fujian",
    label: "福建省",
    children: [
      { value: "fuzhou", label: "福州市" },
      { value: "xiamen", label: "厦门市" },
      { value: "putian", label: "莆田市" },
      { value: "quanzhou", label: "泉州市" },
      { value: "zhangzhou", label: "漳州市" },
      { value: "longyan", label: "龙岩市" },
      { value: "sanming", label: "三明市" },
      { value: "ningde", label: "宁德市" },
    ],
  },
  {
    value: "guangxi",
    label: "广西壮族自治区",
    children: [
      { value: "nanning", label: "南宁市" },
      { value: "guilin", label: "桂林市" },
      { value: "liuzhou", label: "柳州市" },
      { value: "wuzhou", label: "梧州市" },
      { value: "beihai", label: "北海市" },
      { value: "qinzhou", label: "钦州市" },
      { value: "guigang", label: "贵港市" },
      { value: "yulin", label: "玉林市" },
      { value: "baise", label: "百色市" },
      { value: "hechi", label: "河池市" },
      { value: "hezhou", label: "贺州市" },
    ],
  },
  {
    value: "hainan",
    label: "海南省",
    children: [
      { value: "haikou", label: "海口市" },
      { value: "sanya", label: "三亚市" },
      { value: "danzhou", label: "儋州市" },
      { value: "wuzhishan", label: "五指山市" },
      { value: "qionghai", label: "琼海市" },
    ],
  },
  {
    value: "hubei",
    label: "湖北省",
    children: [
      { value: "wuhan", label: "武汉市" },
      { value: "xiangyang", label: "襄阳市" },
      { value: "yichang", label: "宜昌市" },
      { value: "huangshi", label: "黄石市" },
      { value: "ezhou", label: "鄂州市" },
      { value: "shiyan", label: "十堰市" },
      { value: "jianghan", label: "荆门市" },
      { value: "xianning", label: "咸宁市" },
      { value: "jingzhou", label: "荆州市" },
    ],
  },
  {
    value: "hunan",
    label: "湖南省",
    children: [
      { value: "changsha", label: "长沙市" },
      { value: "zhuzhou", label: "株洲市" },
      { value: "xiangtan", label: "湘潭市" },
      { value: "yueyang", label: "岳阳市" },
      { value: "hengyang", label: "衡阳市" },
      { value: "changde", label: "常德市" },
      { value: "yiyang", label: "益阳市" },
      { value: "yongzhou", label: "永州市" },
      { value: "huaihua", label: "怀化市" },
      { value: "shaoyang", label: "邵阳市" },
    ],
  },
  {
    value: "sichuan",
    label: "四川省",
    children: [
      { value: "chengdu", label: "成都市" },
      { value: "mianyang", label: "绵阳市" },
      { value: "ziyang", label: "资阳市" },
      { value: "leshan", label: "乐山市" },
      { value: "yaan", label: "雅安市" },
    ],
  },
  {
    value: "guizhou",
    label: "贵州省",
    children: [
      { value: "guiyang", label: "贵阳市" },
      { value: "zunyi", label: "遵义市" },
    ],
  },
  {
    value: "yunnan",
    label: "云南省",
    children: [
      { value: "kunming", label: "昆明市" },
      { value: "lijiang", label: "丽江市" },
      { value: "dali", label: "大理市" },
      { value: "lincang", label: "临沧市" },
      { value: "dehong", label: "德宏傣族景颇族自治州" },
    ],
  },
  {
    value: "xizang",
    label: "西藏自治区",
    children: [
      { value: "lhasa", label: "拉萨市" },
      { value: "xigaze", label: "日喀则市" },
      { value: "shannan", label: "山南市" },
      { value: "rikaze", label: "阿里地区" },
    ],
  },
  {
    value: "neimenggu",
    label: "内蒙古自治区",
    children: [
      { value: "huhehaote", label: "呼和浩特市" },
      { value: "baotou", label: "包头市" },
      { value: "wuhai", label: "乌海市" },
      { value: "chifeng", label: "赤峰市" },
    ],
  },
  {
    value: "ningxia",
    label: "宁夏回族自治区",
    children: [
      { value: "yinchuan", label: "银川市" },
      { value: "shizuishan", label: "石嘴山市" },
      { value: "wuzhong", label: "吴忠市" },
      { value: "zhongwei", label: "中卫市" },
    ],
  },
  {
    value: "xinjiang",
    label: "新疆维吾尔自治区",
    children: [
      { value: "wulumuqi", label: "乌鲁木齐市" },
      { value: "karamay", label: "克拉玛依市" },
      { value: "shihezi", label: "石河子市" },
      { value: "changji", label: "昌吉回族自治州" },
      {
        value: "bayingolin",
        label: "巴音郭楞蒙古自治州",
        children: [{ value: "bayingolin", label: "库尔勒市" }],
      },
      {
        value: "boertala",
        label: "博尔塔拉蒙古自治州",
        children: [{ value: "boertala", label: "博乐市" }],
      },
      {
        value: "yili",
        label: "伊犁哈萨克自治州",
        children: [{ value: "yili", label: "伊宁市" }],
      },
      {
        value: "tacheng",
        label: "塔城地区",
        children: [{ value: "tacheng", label: "塔城市" }],
      },
      {
        value: "altay",
        label: "阿勒泰地区",
        children: [{ value: "altay", label: "阿勒泰市" }],
      },
    ],
  },
];

export const CITY_OPTIONS = CITIES;
